export const AUTOJOURNALS_GET = 'AUTOJOURNALS_GET';
export const AUTOJOURNAL_CREATE = 'AUTOJOURNAL_CREATE';
export const AUTOJOURNAL_UPDATE = 'AUTOJOURNAL_UPDATE';
export const AUTOJOURNAL_DELETE = 'AUTOJOURNAL_DELETE';
export const AUTOJOURNAL_RESTORE = 'AUTOJOURNAL_RESTORE';
export const AUTOJOURNAL_HARDDEL = 'AUTOJOURNAL_HARDDEL';
export const AUTOJOURNALS_EXPORT = 'AUTOJOURNALS_EXPORT';
export const AUTOJOURNALS_IMPORT = 'AUTOJOURNALS_IMPORT';