export const JOURNALS_GET = 'JOURNALS_GET';
export const JOURNAL_CREATE = 'JOURNAL_CREATE';
export const JOURNAL_UPDATE = 'JOURNAL_UPDATE';
export const JOURNAL_DELETE = 'JOURNAL_DELETE';
export const JOURNAL_RESTORE = 'JOURNAL_RESTORE';
export const JOURNAL_HARDDEL = 'JOURNAL_HARDDEL';
export const JOURNALS_EXPORT = 'JOURNALS_EXPORT';
export const JOURNALS_IMPORT = 'JOURNALS_IMPORT';