export const SAVINGS_GET = 'SAVINGS_GET';
export const SAVING_CREATE = 'SAVING_CREATE';
export const SAVING_UPDATE = 'SAVING_UPDATE';
export const SAVING_DELETE = 'SAVING_DELETE';
export const SAVING_RESTORE = 'SAVING_RESTORE';
export const SAVING_HARDDEL = 'SAVING_HARDDEL';
export const SAVINGS_EXPORT = 'SAVINGS_EXPORT';
export const SAVINGS_IMPORT = 'SAVINGS_IMPORT';