export const MEMBERS_GET = 'MEMBERS_GET';
export const MEMBER_CREATE = 'MEMBER_CREATE';
export const MEMBER_UPDATE = 'MEMBER_UPDATE';
export const MEMBER_DELETE = 'MEMBER_SOFT_DELETE';
export const MEMBER_HARD_DELETE = 'MEMBER_DELETE';
export const MEMBERS_EXPORT = 'MEMBERS_EXPORT';
export const MEMBERS_IMPORT = 'MEMBERS_IMPORT';
export const RESET_IMPORT = 'RESET_EXPORT';