export const SUPERVISORS_GET = 'SUPERVISORS_GET';
export const SUPERVISOR_UPDATE = 'SUPERVISOR_UPDATE';
export const SUPERVISOR_SET = 'SUPERVISOR_SET';
export const SUPERVISOR_UNSET = 'SUPERVISOR_UNSET';