export const RECEPTIONS_GET = 'RECEPTIONS_GET';
export const RECEPTION_CREATE = 'RECEPTION_CREATE';
export const RECEPTION_UPDATE = 'RECEPTION_UPDATE';
export const RECEPTION_DELETE = 'RECEPTION_DELETE';
export const RECEPTION_RESTORE = 'RECEPTION_RESTORE';
export const RECEPTION_HARDDEL = 'RECEPTION_HARDDEL';
export const RECEPTIONS_EXPORT = 'RECEPTIONS_EXPORT';
export const RECEPTIONS_IMPORT = 'RECEPTIONS_IMPORT';