export const ACCOUNTS_GET = 'ACCOUNTS_GET';
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';
export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNT_DELETE = 'ACCOUNT_SOFT_DELETE';
export const ACCOUNT_HARD_DELETE = 'ACCOUNT_DELETE';
export const ACCOUNTS_EXPORT = 'ACCOUNTS_EXPORT';
export const ACCOUNTS_IMPORT = 'ACCOUNTS_IMPORT';